package com.rarilabs.rarime.ui.components

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.rarilabs.rarime.ui.theme.RarimeTheme
import dev.jeziellago.compose.markdowntext.MarkdownText

val MARKDOWN_CONTENT = buildString {
    append("###  Features\n")
    append("\n")
    append("- Support Standard Markdown / CommonMark and GFM(GitHub Flavored Markdown);\n")
    append("- Full-featured: Real-time Preview, Image (cross-domain) upload, Preformatted text/Code blocks/Tables insert, Code fold, Search replace, Read only, Themes, Multi-languages, L18n, HTML entities, Code syntax highlighting...;\n")
    append("- Markdown Extras : Support ToC (Table of Contents), Emoji, Task lists, @Links...;\n")
    append("- Compatible with all major browsers (IE8+), compatible Zepto.js and iPad;\n")
    append("- Support identification, interpretation, fliter of the HTML tags;\n")
    append("- Support TeX (LaTeX expressions, Based on KaTeX), Flowchart and Sequence Diagram of Markdown extended syntax;\n")
    append("- Support AMD/CMD (Require.js & Sea.js) Module Loader, and Custom/define editor plugins;\n")
    append("\n")
    append("# Editor.md\n")
    append("\n")
    append("![](https://pandao.github.io/editor.md/images/logos/editormd-logo-180x180.png)\n")
    append("\n")
    append("![](https://img.shields.io/github/stars/pandao/editor.md.svg) ![](https://img.shields.io/github/forks/pandao/editor.md.svg) ![](https://img.shields.io/github/tag/pandao/editor.md.svg) ![](https://img.shields.io/github/release/pandao/editor.md.svg) ![](https://img.shields.io/github/issues/pandao/editor.md.svg) ![](https://img.shields.io/bower/v/editor.md.svg)\n")
    append("\n")
    append("\n")
    append("**Table of Contents**\n")
    append("\n")
    append("[TOCM]\n")
    append("\n")
    append("[TOC]\n")
    append("\n")
    append("# H1 header\n")
    append("## H2 header\n")
    append("### H3 header\n")
    append("#### H4 header\n")
    append("##### H5 header\n")
    append("###### H6 header\n")
    append("# Heading 1 link [Heading link](https://github.com/pandao/editor.md \"Heading link\")\n")
    append("## Heading 2 link [Heading link](https://github.com/pandao/editor.md \"Heading link\")\n")
    append("### Heading 3 link [Heading link](https://github.com/pandao/editor.md \"Heading link\")\n")
    append("#### Heading 4 link [Heading link](https://github.com/pandao/editor.md \"Heading link\") Heading link [Heading link](https://github.com/pandao/editor.md \"Heading link\")\n")
    append("##### Heading 5 link [Heading link](https://github.com/pandao/editor.md \"Heading link\")\n")
    append("###### Heading 6 link [Heading link](https://github.com/pandao/editor.md \"Heading link\")\n")
    append("\n")
    append("## Headers (Underline)\n")
    append("\n")
    append("H1 Header (Underline)\n")
    append("=============\n")
    append("\n")
    append("H2 Header (Underline)\n")
    append("-------------\n")
    append("\n")
    append("### Characters\n")
    append("                \n")
    append("----\n")
    append("\n")
    append("~~Strikethrough~~ <s>Strikethrough (when enable html tag decode.)</s>\n")
    append("*Italic*      _Italic_\n")
    append("**Emphasis**  __Emphasis__\n")
    append("***Emphasis Italic*** ___Emphasis Italic___\n")
    append("\n")
    append("Superscript: X<sub>2</sub>，Subscript: O<sup>2</sup>\n")
    append("\n")
    append("**Abbreviation(link HTML abbr tag)**\n")
    append("\n")
    append("The <abbr title=\"Hyper Text Markup Language\">HTML</abbr> specification is maintained by the <abbr title=\"World Wide Web Consortium\">W3C</abbr>.\n")
    append("\n")
    append("### Blockquotes\n")
    append("\n")
    append("> Blockquotes\n")
    append("\n")
    append("Paragraphs and Line Breaks\n")
    append("                    \n")
    append("> \"Blockquotes Blockquotes\", [Link](http://localhost/)。\n")
    append("\n")
    append("### Links\n")
    append("\n")
    append("[Links](http://localhost/)\n")
    append("\n")
    append("[Links with title](http://localhost/ \"link title\")\n")
    append("\n")
    append("`<link>` : <https://github.com>\n")
    append("\n")
    append("[Reference link][id/name] \n")
    append("\n")
    append("[id/name]: http://link-url/\n")
    append("\n")
    append("GFM a-tail link @pandao\n")
    append("\n")
    append("### Code Blocks (multi-language) & highlighting\n")
    append("\n")
    append("### #Inline code\n")
    append("\n")
    append("`\$ npm install marked`\n")
    append("\n")
    append("### #Code Blocks (Indented style)\n")
    append("\n")
    append("Indented 4 spaces, like `<pre>` (Preformatted Text).\n")
    append("\n")
    append("    <?php\n")
    append("        echo \"Hello world!\";\n")
    append("    ?>\n")
    append("    \n")
    append("Code Blocks (Preformatted text):\n")
    append("\n")
    append("    | First Header  | Second Header |\n")
    append("    | ------------- | ------------- |\n")
    append("    | Content Cell  | Content Cell  |\n")
    append("    | Content Cell  | Content Cell  |\n")
    append("\n")
    append("### #Javascript　\n")
    append("\n")
    append("```javascript\n")
    append("function test(){\n")
    append("\tconsole.log(\"Hello world!\");\n")
    append("}\n")
    append(" \n")
    append("(function(){\n")
    append("    var box = function(){\n")
    append("        return box.fn.init();\n")
    append("    };\n")
    append("\n")
    append("    box.prototype = box.fn = {\n")
    append("        init : function(){\n")
    append("            console.log('box.init()');\n")
    append("\n")
    append("\t\t\treturn this;\n")
    append("        },\n")
    append("\n")
    append("\t\tadd : function(str){\n")
    append("\t\t\talert(\"add\", str);\n")
    append("\n")
    append("\t\t\treturn this;\n")
    append("\t\t},\n")
    append("\n")
    append("\t\tremove : function(str){\n")
    append("\t\t\talert(\"remove\", str);\n")
    append("\n")
    append("\t\t\treturn this;\n")
    append("\t\t}\n")
    append("    };\n")
    append("    \n")
    append("    box.fn.init.prototype = box.fn;\n")
    append("    \n")
    append("    window.box =box;\n")
    append("})();\n")
    append("\n")
    append("var testBox = box();\n")
    append("testBox.add(\"jQuery\").remove(\"jQuery\");\n")
    append("```\n")
    append("\n")
    append("### #HTML code\n")
    append("\n")
    append("```html\n")
    append("<!DOCTYPE html>\n")
    append("<html>\n")
    append("    <head>\n")
    append("        <mate charest=\"utf-8\" />\n")
    append("        <title>Hello world!</title>\n")
    append("    </head>\n")
    append("    <body>\n")
    append("        <h1>Hello world!</h1>\n")
    append("    </body>\n")
    append("</html>\n")
    append("```\n")
    append("\n")
    append("### Images\n")
    append("\n")
    append("Image:\n")
    append("\n")
    append("![](https://pandao.github.io/editor.md/examples/images/4.jpg)\n")
    append("\n")
    append("> Follow your heart.\n")
    append("\n")
    append("![](https://pandao.github.io/editor.md/examples/images/8.jpg)\n")
    append("\n")
    append("> 图为：厦门白城沙滩 Xiamen\n")
    append("\n")
    append("图片加链接 (Image + Link)：\n")
    append("\n")
    append("[![](https://pandao.github.io/editor.md/examples/images/7.jpg)](https://pandao.github.io/editor.md/examples/images/7.jpg \"李健首张专辑《似水流年》封面\")\n")
    append("\n")
    append("> 图为：李健首张专辑《似水流年》封面\n")
    append("                \n")
    append("----\n")
    append("\n")
    append("### Lists\n")
    append("\n")
    append("#### Unordered list (-)\n")
    append("\n")
    append("- Item A\n")
    append("- Item B\n")
    append("- Item C\n")
    append("     \n")
    append("#### Unordered list (*)\n")
    append("\n")
    append("* Item A\n")
    append("* Item B\n")
    append("* Item C\n")
    append("\n")
    append("#### Unordered list (plus sign and nested)\n")
    append("                \n")
    append("+ Item A\n")
    append("+ Item B\n")
    append("    + Item B 1\n")
    append("    + Item B 2\n")
    append("    + Item B 3\n")
    append("+ Item C\n")
    append("    * Item C 1\n")
    append("    * Item C 2\n")
    append("    * Item C 3\n")
    append("\n")
    append("#### Ordered list\n")
    append("                \n")
    append("1. Item A\n")
    append("2. Item B\n")
    append("3. Item C\n")
    append("                \n")
    append("----\n")
    append("                    \n")
    append("### Tables\n")
    append("                    \n")
    append("First Header  | Second Header\n")
    append("------------- | -------------\n")
    append("Content Cell  | Content Cell\n")
    append("Content Cell  | Content Cell \n")
    append("\n")
    append("| First Header  | Second Header |\n")
    append("| ------------- | ------------- |\n")
    append("| Content Cell  | Content Cell  |\n")
    append("| Content Cell  | Content Cell  |\n")
    append("\n")
    append("| Function name | Description                    |\n")
    append("| ------------- | ------------------------------ |\n")
    append("| `help()`      | Display the help window.       |\n")
    append("| `destroy()`   | **Destroy your computer!**     |\n")
    append("\n")
    append("| Item      | Value |\n")
    append("| --------- | -----:|\n")
    append("| Computer  | \$1600 |\n")
    append("| Phone     |   \$12 |\n")
    append("| Pipe      |    \$1 |\n")
    append("\n")
    append("| Left-Aligned  | Center Aligned  | Right Aligned |\n")
    append("| :------------ |:---------------:| -----:|\n")
    append("| col 3 is      | some wordy text | \$1600 |\n")
    append("| col 2 is      | centered        |   \$12 |\n")
    append("| zebra stripes | are neat        |    \$1 |\n")
    append("                \n")
    append("----\n")
    append("\n")
    append("#### HTML entities\n")
    append("\n")
    append("&copy; &  &uml; &trade; &iexcl; &pound;\n")
    append("&amp; &lt; &gt; &yen; &euro; &reg; &plusmn; &para; &sect; &brvbar; &macr; &laquo; &middot; \n")
    append("\n")
    append("X&sup2; Y&sup3; &frac34; &frac14;  &times;  &divide;   &raquo;\n")
    append("\n")
    append("18&ordm;C  &quot;  &apos;\n")
    append("\n")
    append("## Escaping for Special Characters\n")
    append("\n")
    append("\\*literal asterisks\\*\n")
    append("\n")
    append("###  End")
}

@Composable
fun UiMarkdown(markdown: String) {
    MarkdownText(
        markdown = markdown
    )
}

@Preview
@Composable
fun UiMarkdownPreview() {
    Column (
        modifier = Modifier
            .fillMaxSize()
            .background(RarimeTheme.colors.backgroundPrimary)
            .padding(20.dp)
            .verticalScroll(rememberScrollState())
    ) {
        UiMarkdown(MARKDOWN_CONTENT)
    }
}